// packages/svelte/src/lib/components/OrganizationSwitcher.svelte
<script lang="ts">
  import { useAtlas } from '../context';
  import { getOrganization } from '../accessors';
  import { classFor } from '../appearance';
  import { translate } from '../i18n';

  /** §10.2 `<OrganizationSwitcher/>` — switch the active organization. */
  const atlas = useAtlas();
  const org = getOrganization();
  const t = (key: string) => translate(atlas.catalog, key);

  $: menuClass = classFor('menu', atlas.appearance, 'atlas-menu');
  $: itemClass = classFor('menuItem', atlas.appearance, 'atlas-menu-item');
</script>

<div class={menuClass}>
  <button class={itemClass} on:click={() => void $org.setActive(null)}>
    {t('organization.personal')}
  </button>
  {#each $org.memberships as membership (membership.organization.id)}
    <button
      class={itemClass}
      disabled={membership.organization.id === $org.organization?.id}
      on:click={() => void $org.setActive(membership.organization.id)}
    >
      {membership.organization.name}
    </button>
  {/each}
</div>

// packages/angular/src/lib/components/organization-switcher.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { AtlasService } from '../atlas.service';
import { classFor, type ElementKey } from '../appearance';
import { translate } from '../i18n';

/**
 * `<atlas-organization-switcher>` — switch the active organization (or the
 * personal account). The Angular peer of React's `<OrganizationSwitcher/>`.
 */
@Component({
  selector: 'atlas-organization-switcher',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="cls('menu', 'atlas-menu')">
      <button [class]="cls('menuItem', 'atlas-menu-item')" (click)="setActive(null)">
        {{ t('organization.personal') }}
      </button>
      @for (membership of atlas.memberships(); track membership.organization.id) {
        <button
          [class]="cls('menuItem', 'atlas-menu-item')"
          [disabled]="membership.organization.id === atlas.organization()?.organization?.id"
          (click)="setActive(membership.organization.id)"
        >
          {{ membership.organization.name }}
        </button>
      }
    </div>
  `,
})
export class OrganizationSwitcherComponent {
  protected readonly atlas = inject(AtlasService);

  protected t(key: string): string {
    return translate(this.atlas.localization, key);
  }

  protected cls(key: ElementKey, base: string): string {
    return classFor(key, this.atlas.appearance, base);
  }

  protected setActive(organizationId: string | null): void {
    void this.atlas.setActiveOrganization(organizationId);
  }
}
