// packages/svelte/src/lib/components/OrganizationProfile.svelte
<script lang="ts">
  import { useAtlas } from '../context';
  import { getOrganization } from '../accessors';
  import { classFor } from '../appearance';
  import { translate } from '../i18n';
  import Protect from './Protect.svelte';

  /** §10.2 `<OrganizationProfile/>` — the active organization's card. */
  const atlas = useAtlas();
  const org = getOrganization();
  const t = (key: string) => translate(atlas.catalog, key);

  $: cardClass = classFor('card', atlas.appearance, 'atlas-card');
</script>

{#if $org.organization}
  <div class={cardClass}>
    <h1>{$org.organization.name}</h1>
    <p>{t('organization.roleLabel')}: {$org.membership?.role}</p>
    <!-- Management controls are gated on the ACTIVE org role, matching the
         server's §9.2 rule rather than duplicating a looser one. -->
    <Protect permission="org:sys_memberships:manage">
      <button>{t('organization.invite')}</button>
    </Protect>
  </div>
{/if}

// packages/angular/src/lib/components/organization-profile.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { AtlasService } from '../atlas.service';
import { AtlasProtectDirective } from '../directives/protect.directive';
import { classFor, type ElementKey } from '../appearance';
import { translate } from '../i18n';

/**
 * `<atlas-organization-profile>` — the active organization's surface. The
 * Angular peer of React's `<OrganizationProfile/>`. Management controls are
 * gated on the ACTIVE org role via `*atlasProtect`, matching the server's rule
 * rather than duplicating a looser one. Renders nothing with no active org.
 */
@Component({
  selector: 'atlas-organization-profile',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AtlasProtectDirective],
  template: `
    @if (atlas.organization(); as membership) {
      <div [class]="cls('card', 'atlas-card')">
        <h1>{{ membership.organization.name }}</h1>
        <p>{{ t('organization.roleLabel') }}: {{ membership.role }}</p>

        <button *atlasProtect="{ permission: 'org:sys_memberships:manage' }">
          {{ t('organization.invite') }}
        </button>
      </div>
    }
  `,
})
export class OrganizationProfileComponent {
  protected readonly atlas = inject(AtlasService);

  protected t(key: string): string {
    return translate(this.atlas.localization, key);
  }

  protected cls(key: ElementKey, base: string): string {
    return classFor(key, this.atlas.appearance, base);
  }
}
